version: '3'
services:
  # serviceregistry:
  #   image: 'eljoamy/serviceregistry:0.0.1'
  #   container_name: serviceregistry
  #   ports:
  #     - '8761:8761'
  
  # cloudgateway:
  #   image: 'eljoamy/cloudgateway:0.0.1'
  #   container_name: cloudgateway
  #   ports:
  #     - '9090:9090'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #   depends_on:
  #     - serviceregistry
  
  # adminservice:
  #   image: 'eljoamy/adminservice:0.0.1'
  #   container_name: adminservice
  #   ports:
  #     - '8586:8586'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #   depends_on:
  #     - serviceregistry

  # authservice:
  #   image: 'eljoamy/authservice:0.0.1'
  #   container_name: authservice
  #   ports:
  #     - '8585:8585'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #   depends_on:
  #     - serviceregistry
  #     - adminservice
  
  # reservationservice:
  #   image: 'eljoamy/reservationservice:0.0.1'
  #   container_name: reservationservice
  #   ports:
  #     - '8588:8588'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #   depends_on:
  #     - serviceregistry
  #     # - adminservice
  #     # - authservice

  # notificationservice:
  #   image: 'eljoamy/notificationservice:0.0.1'
  #   container_name: notificationservice
  #   ports:
  #     - '8587:8587'
  #   environment:
  #     - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
  #   depends_on:
  #     - serviceregistry
  #     # - adminservice
  #     # - authservice

  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,cloudformation,sts,apigateway,iam,route53
    ports:
      - "4566-4597:4566-4597"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"